baseURL = 'https://AGHILES667.github.io/Hugo-Projet/'
languageCode = 'en-us'
title = "Aghiles's Website"
theme = 'beautifulhugo'
languagecode = "en"





# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "docs/"
